---

- hosts: all
  become: true
  pre_tasks:

    - name: yum and epel installation
      yum:
        name:
          - epel-release
          - yum
      when: ansible_distribution == "CentOS"

    - name: dpkg in ubuntu
      shell: |
        dpkg --configure -a
      when: ansible_distribution == "Ubuntu"

    - name: install updates (CentOS)
      yum:
        update_cache: yes
        update_only: yes
      when: ansible_distribution == "CentOS"

    - name: install updates (Ubuntu)
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

- hosts: ubuntu_nagios
  become: true
  roles:
    - ubuntu_server

- hosts: centos_nagios
  become: true
  roles:
    - centos_server

